version: '3.8'

services:
  discussai:
    image: bentwng/discussai:latest
    container_name: discussai
    restart: always
    ports:
      - "8220:8000"
    volumes:
      - /home/ncadmin/discussai:/app/.gradio
      - /home/ncadmin/discussai_files:/app/gradio_cached_files
    environment:
      OPENAI_BASE_URL: https://api.mr5ai.com/v1
      OPENAI_API_KEY: sk-xxx
      OPENAI_MODEL_NORMAL: gemini-3-flash
      OPENAI_MODEL_DEEP: gpt-5.1
